### ISSUE TITLE
UI Logout action resolves to argocd.example.com URL

### ISSUE THREAD

**Issue by fwdolegp** [argoproj/argo-helm#1178]
### Describe the bug

UI Logout action resolve to argocd.example.com URL

### Related helm chart

argo-cd

### To Reproduce

Install with helm chart.
Login with admin and autogenerated password.
Click logout link
web browser navigates to argocd.example.com

### Expected behavior

Expected: navigates to login screen 

### Additional context

works as expected after running this:

kubectl -n argocd patch configmap argocd-cm  --type=json -p='[{"op": "remove", "path": "/data/url"}]'

**Comment by mkilchhofer** [comment]
related to #1169

**Comment by dbaltor** [comment]
I'm running ArgoCD **v2.9.3** deployed via helm char **v3.35.4** from [here](https://argoproj.github.io/argo-helm/) and can confirm this behaviour still happens regardless of the PR above. To fix it, I had to configure the values.yaml as per below:
```
server:
  config:
    url: "<ARGO_URL>"
```

**Comment by HomeLabJunkie** [comment]
I've installed and am testing v3.2.0+66b2f30 and when I click on logout it sends me to argocd.example.com still in 2025 ? is there no fix for this ? tried the config: option above with no change.

**Comment by meilinkm-personal** [comment]
@HomeLabJunkie Perhaps it changed, but this works for me:

```
global:
    domain: argocd.domain.tld
```
If you look at the values.yaml file in the ArgoCD Helm chart, [https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml]([https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml]), there is no "server.config.url" entry at all, so that is why I'm saying, maybe it changed. Once I added the "global.domain" entry and ran 'helm upgrade --install argocd argo/argo-cd -n argocd -f values.yaml', the logout button no longer refers to argocd.example.com.
