### ISSUE TITLE
Allow annotations in repository credentials

### ISSUE THREAD

**Issue by Faizan27** [argoproj/argo-helm#1280]
### Is your feature request related to a problem?

While using argocd-vault-plugin we need annotations to define paths, we can use inline too which is a workaround but it would be great to have annotations block in repository credentials or by far any secrets which we use in the argo-cd/argocd-configs/ folder.

### Related helm chart

argo-cd

### Describe the solution you'd like

The current solution in production that I have implemented is
adding the following in repository-credentials template.yaml
```
  {{- if $.Values.configs.annotations }}
  annotations:
  {{- range $key, $value := $.Values.configs.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
```

[suggestion.txt](https://github.com/argoproj/argo-helm/files/8702804/suggestion.txt)

### Describe alternatives you've considered

The workaround can be to use inline path instead of annotations path with the plugin currently. But it would be great to have the ability to add annotations to secrets.

**Comment by dtotopus** [comment]
I would say new repo config for sure is an issue. E.g https://argo-cd.readthedocs.io/en/latest/operator-manual/declarative-setup/#legacy-behaviour deprecation pretty much allows only plain ssh keys compared to what "legacy" config maps allowed to configure.

It seems defining secrets that are generated by e.g. secret store csi plugin won't be possible anymore as it requires references instead of plain ssh like
```
...
  repository.credentials: |  
  - url: git@repo_address  
    sshPrivateKeySecret:  
      name: secretName  
      key: secretKey
```
