### ISSUE TITLE
specify image registry for haproxy

### ISSUE THREAD

**Issue by lknite** [argoproj/argo-helm#1282]
### Is your feature request related to a problem?

I need to be able to use a local repo to pull haproxy from, otherwise it will fail.  In my situation this is because of resource limits on dockerhub & the need to use a proxy instead.

### Related helm chart

argo-cd

### Describe the solution you'd like

To have haproxy mirrored at quay so there is no special dockerhub pull for that one.
or
To have a place in the values.yaml to specify an image repo for haproxy.

### Describe alternatives you've considered

I modified the deployment after the fact to get things working, but this of course is not practical.  I see there is a global repo but if I change that then application-controller, notiications-controller, argocd-repo-server, and argocd-server fail to pull successfully.  I suppose I could change the default, then update the 4 additional deployments to use quay... but it's not exactly clear to me immediately how to do this.  I could also potentially manually place the needed additional images on my local repo, but at this time that would be difficult to maintain.

**Comment by pdrastil** [comment]
The `haproxy` is subchart from [here](https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/values.yaml). If you expect that `global.image` will work than sadly it's not possible due to how Helm sub-charts work. The only way would be to completely reimplement haproxy as part of Argo CD chart which brings more maintenance overhead or just specify the following section in your values.yaml overrides

```yml
redis-ha:
  enabled: true
  image:
    repository: docker.mirror.acme.com/redis
```
