### ISSUE TITLE
Use NodePort instead of ClusterIP for AWS ALB gRPC

### ISSUE THREAD

**Issue by sebastianmacarescu** [argoproj/argo-helm#1514]
### Describe the bug

Documentation from here https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#using-aws-alb-ingress-controller-with-grpc specfies to use `serviceType: ClusterIP`.
With this I get the following error on the ingress:
`Failed deploy model due to InvalidParameter: 1 validation error(s) found. - minimum field value of 1, CreateTargetGroupInput.Port.`

Changing to `NodePort` fixes the issue

### Related helm chart

argo-cd

### Helm chart version

5.4.0

### To Reproduce

1. Go to https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#using-aws-alb-ingress-controller-with-grpc
2. Deploy argo helm with specified config
3. Check ingress status in AWS

### Expected behavior

Have the alb rules properly created

### Screenshots

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/6714842/194338924-2b85582b-b5bc-4362-8b49-fbd5188aaf5f.png">

**Comment by pdrastil** [comment]
Hi @sebastianmacarescu thanks for reporting this. Current ingress implementation is quite confusing because it combines features for different controllers (nginx, aws, gcp, etc.) Could I ask you to take a look on https://github.com/argoproj/argo-helm/pull/1474 where this was cleaned up and verify that docs / settings for ALB actually works as I don't use AWS cloud and docs is on point?

**Comment by mkilchhofer** [comment]
Hmmm I am not sude if it is supported to use NodePort on the gRPC service when you add "alb.ingress.kubernetes.io/target-type: ip" on the ingress level. Maybe you should remove that annotation or don't use NodePort.
