### ISSUE TITLE
Copyutil container resources should be configurable within separate/isolated values block

### ISSUE THREAD

**Issue by yevhen-harmonizehr** [argoproj/argo-helm#1618]
### Is your feature request related to a problem?

Lets take repo-server component: both repo-server and copyutil containers re-uses same values from repoServer.resources blocks. So if i want so set bigger values for repo-server i am automatically changes those values for copyutil. In some cases it might lead to bigger nodes rollout.

### Related helm chart

argo-cd

### Describe the solution you'd like

Just a separate block inside repoServer would help. repoServer.copyutil.resources

**Comment by pdrastil** [comment]
@yevhen-harmonizehr This is intentional. Both images are the same and function for scheduler looks as follows:

SUM(MAX(init_container_resources), SUM(container_resources))

In example where you set 64Mi for repo-server the K8s control plane will request only 64Mi

SUM(MAX(64Mi), SUM(64Mi)) = SUM(64Mi) = 64Mi will be requested

**Comment by pdrastil** [comment]
Ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources

**Comment by yevhen-harmonizehr** [comment]
@pdrastil  okay, that makes sense now, thank you and sorry for inconvenienc

**Comment by pdrastil** [comment]
No problem, I originally also thought it's sum of everything ;)
