### ISSUE TITLE
Trouble installing Argocd on kubernetes 1.21

### ISSUE THREAD

**Issue by anilnokia** [argoproj/argo-helm#1657]
### Describe the bug

I am trying to install argocd but it does not work on Kubernetes 1.21. Is it possible to make it work on this version? I was able to install it few weeks ago but not anymore. 

helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace --values values-proxy.yaml
Release "argocd" does not exist. Installing it now.
Error: chart requires kubeVersion: >=1.22.0-0 which is incompatible with Kubernetes v1.21.14

### Related helm chart

argo-cd

### Helm chart version

5.14.1

### To Reproduce

install kubrnetes 1.21

helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace

### Expected behavior

chart installed successfully

**Comment by pdrastil** [comment]
Hi, 
this is intentional. This is upstream reference for [supported versions](https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#supported-versions) and this [thread](https://github.com/argoproj/argo-helm/pull/1579#pullrequestreview-1156074508) that lead to decision to enforce K8s 1.22.
