### ISSUE TITLE
CRD installation via helm hooks deprecated in Helm v3

### ISSUE THREAD

**Issue by seanson** [argoproj/argo-helm#169]
**Describe the bug**
With the release of Helm3 our users are starting to hit some issues with CRD installation that relied on the hook `"helm.sh/hook": crd-install`

**To Reproduce**
```
helm install argo/argo-cd 
Release "argocd" does not exist. Installing it now.
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
```

**Expected behavior**
CRDs are installed as part of chart installation.

**Additional context**
The current suggested backwards-compatible solution as per https://github.com/helm/helm/pull/6243 is to create a new directory called `crds` and place the CRD resources in there. We should find a way to maintain backwards compatibility with Helm v2 for a minimum amount of time though.

**Comment by shawnzhu** [comment]
## Problem

Checkout the article [Custom Resource Definitions - Chart Best Practices](https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you):

> With the arrival of Helm 3, we removed the old `crd-install` hooks for a more simple methodology.

So when installing this argo-cd chart (uses `crd-install` hook) via helm v3, CRDs will **not** be installed. I had this problem that causes argocd-server keeps crashing where the pod logs shows it could not found CRD resource `appprojects.argoproj.io`.

I could not find a way to maintain backwards compatibility to supports both Helm v2 and v3 with current chart `argo-cd` since Helm v3 will ignore `crd-install` hooks nor support templatized CRD resource.

## My solution 
By Following [Method 2: Separate Charts](https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/#method-2-separate-charts), I created a separate chart named `argo-crds` that contains directory `crds` for the two CRDs plus a simple `Chart.yaml`. Then run `helm install <release-name> argo-crds` to install CRDs before installing `argo-cd` chart into a specific namespace via Helm v3.

If ☝️path is reasonable, I'm happy to create a PR

**Comment by CarpathianUA** [comment]
Experiencing the same with Helm 3. @shawnzhu I guess your PR will be very helpful!

**Comment by foobarbecue** [comment]
New argo-events user here. I almost gave up on argo entirely because of this issue. I added a PR to the argo-events doc for the moment to prevent other people from getting as confused as I did: https://github.com/argoproj/argo-events/pull/416 also discussed here: https://argoproj.slack.com/archives/CAM37QYMS/p1575483739308500

**Comment by jendrikjoe** [comment]
Am seeing the same issue installing `argo/argo`

**To Reproduce**
```
helm install argo argo/argo --namespace=argo
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
```

**Comment by emaildanwilson** [comment]
At the very least we should make helm template ignore this error and still produce the CRD's

**Comment by seanson** [comment]
Helm v3 support should now be good with the dedicated CRDs directory, please raise an issue if anyone runs into additional trouble.

**Comment by shibumi** [comment]
@seanson any explanation for this?:

```
❯ helm install stable/prometheus-operator -n monitoring -g
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: create: failed to create: namespaces "monitoring" not found


❯ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"dirty", GoVersion:"go1.14.1"}
chris motoko ~ 19:43:31 180d4a67 master  
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"2020-02-29T16:37:45Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by shay-berman** [comment]
I hit the same helm install issue that @shibumi commented above.

```
helm install shay stable/prometheus-operator
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"

```

but after the installation it looks like the CRDs where installed

```
kubectl get customresourcedefinitions.apiextensions.k8s.io | grep monitoring
alertmanagers.monitoring.coreos.com            2020-04-14T09:21:51Z
podmonitors.monitoring.coreos.com              2020-04-14T09:21:52Z
prometheuses.monitoring.coreos.com             2020-04-14T09:21:53Z
prometheusrules.monitoring.coreos.com          2020-04-14T09:21:53Z
servicemonitors.monitoring.coreos.com          2020-04-14T09:21:54Z
thanosrulers.monitoring.coreos.com             2020-04-14T09:21:55Z
```

Any idea what is this skipping info messages?

**Comment by shibumi** [comment]
@shay-berman my current explanation is:

These hooks are only necessary in helm v2 and helm v3 seem to deploy the CRDs differently.

**Comment by shay-berman** [comment]
Thanks @shibumi , maybe its better to avoid the hooks if its helm3 (so no warning will jump to console). just a suggestion.
