### ISSUE TITLE
CURRENT SYNC STATUS UNKOWN

### ISSUE THREAD

**Issue by franckya** [argoproj/argo-helm#1697]
### Describe the bug

Hi, 
I am getting this error after my deployment and would like to know how this can be resolved. I have seen this as a bug from other people and was wondering if someone can assist. 
Best,
YD.

### Related helm chart

argo-cd

### Helm chart version

v3.10.1

### To Reproduce

N/A

### Expected behavior

N/A

### Screenshots

<img width="1439" alt="Screen Shot 2022-12-09 at 2 10 16 PM" src="https://user-images.githubusercontent.com/67871275/206779543-f57bdafc-5b6b-4756-aa0e-7de71673768a.png">

### Additional context

Not sure

**Comment by yu-croco** [comment]
Hi @franckya ,
I cannot guess the reason because there is no logs.
I think you can get more information by clicking `1 Error` or checking Argo CD server's log. 

<img width="844" alt="Screenshot 2022-12-10 at 22 46 48" src="https://user-images.githubusercontent.com/30188755/206858468-f8b57761-3869-4380-9a06-6632e2e944e6.png">
