### ISSUE TITLE
Upgrading from argo-cd helm chart from 3.10.0 to 4.10.9 results in missing application-controller

### ISSUE THREAD

**Issue by drozd-A** [argoproj/argo-helm#1765]
### Describe the bug

When upgrading argocd to using the v4.10.9 helm chart, the argocd application gets stuck.

The argocd application-controller pod probably deleted the argocd application-controller deployment which included itself before creating an application-controller statefulset which would have been able to continue the process.

### Related helm chart

argo-cd

### Helm chart version

4.10.9

### To Reproduce

1. Set up argocd with the helm chart running 3.10.0
2. Attempt to upgrade argocd to the 4.10.9 version of the argo-cd helm chart
3. View argocd application in argocd and notice a missing application-controller (and sync operations do not work)

### Expected behavior

Upgrade should result in working argocd. If the application-controller going missing is a likely outcome or not possible to avoid/fix, it should be documented in the release notes.

**Comment by pdrastil** [comment]
Hi thanks for pointing this out. This behaviour will be most likely caused by switch from Deployment to StatefulSet for application controller that happened between versions. It seems that your run Argo CD that self-manages itself so it's possible that these pods were removed first and for that reason the controller that would self-update itself is missing. This behaviour should be placed into documentation as user needs to start this component again to restore the operation.

**Comment by pdrastil** [comment]
Tested with following commands and default values without repro.

```sh
helm install argocd argo/argo-cd --version 3.10.0
helm upgrade argocd argo/argo-cd --version 4.10.9
```
