### ISSUE TITLE
Improve probes for all ArgoCD pods

### ISSUE THREAD

**Issue by jowko** [argoproj/argo-helm#1827]
### Is your feature request related to a problem?

Not all ArgoCD pods have defined probes, like livenessProbe or readinessProbe. I also did not saw usage of startupProbe anywhere.
When some pod will be unhealthy, it should be automatically restarted by k8s but it may not happen because lack of the probes.

### Related helm chart

argo-cd

### Describe the solution you'd like

To improve the stability of ArgoCD application, we could increase amount of probes.

For initial startup of service, we can introduce `startupProbe`: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
And remove or decrease `initialDelaySeconds` for other probes.

Dex service has probes defined but they are disabled by default. I think that this should be changed, since in values.yaml there is such entry:
```
  ## Probes for Dex server
  ## Supported from Dex >= 2.28.0
  livenessProbe:
    # -- Enable Kubernetes liveness probe for Dex >= 2.28.0
    enabled: false
```
Current version uses dex v2.35.3. So this could be enabled by default.

Also, these deployments does not have any probes defined:
- argocd-redis
- argocd-notifications

Parameters for these probes should be configurable too, like for existing probes.

### Describe alternatives you've considered

Patching these resources manually.

**Comment by pdrastil** [comment]
Hi @jowko see following:

1) Dex must have probes disabled. If user do not supply valid dex configuration the `argocd-dex` util will not start the server and container will start crash looping as probe ports are not exposed. This unfortunately breaks PR checks. 
2) Application controller probe was recently removed based on upstream choice as HA setups might cause crash looping due to slow response when the controller is under heavy load.
3) Notifications do not have valid health check port (see https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-notification/commands/controller.go ) but we could try to use metrics port if it's actually working.
4) Redis probe really depends on redis-cli command. We could also try to implement this but generally single Redis pod is really for testing things than for production use as it's single point of failure. I would recommend to use redis-ha or external redis that have these features implemented.

**Comment by jowko** [comment]
1. We could add additional info in values.yaml about that. I checked that probe on older version of helm chart and indeed it is crash looping.
2. In case of slow response time, we can increase default value for `timeoutSeconds` property in health checks. It is common to see that this default value is overridden in many helm charts to higher values to couple with such issues. 
4. Thanks for the info.

**Comment by jowko** [comment]
Issue is not resolved yet.

**Comment by jmeridth** [comment]
PRa welcome
