### ISSUE TITLE
Changing contents of existing argocd-secret breaks config

### ISSUE THREAD

**Issue by james-emerton** [argoproj/argo-helm#200]
**Describe the bug**
I'm using Pulumi to bootstrap a cluster running ArgoCD via this chart. (For the purposes of this issue, this should be functionally equivalent to `helm template ... | kubectl apply -f -`.) I've found that if I change the content of `argocd-secret` after the initial deployment ArgoCD will fail to allow login with errors like:

    admin.password is missing

or:

    server.secretkey is missing

Restarting the `argocd-server` pod will cause it to add the missing keys and the problem is resolved.

I'm not certain if this is ultimately an issue for this chart or for ArgoCD proper, or perhaps just a documentation issue, but my searches failed to turn up anything relevant so hopefully this will at the very least help the next person.

**To Reproduce**
1. Deploy argocd chart with no values for `configs.secret`
2. Add some value to `configs.secret` and redeploy
3. Open the ArgoCD web ui to see one of the above errors

**Expected behavior**
Perhaps a `post-upgrade` hook could restart the `argocd-server` pod?

**Comment by seanson** [comment]
This happens because ArgoCD Server will fill in missing secret key values on boot, so your application will deploy with an empty secret, fill in missing secret values on boot, have the secret values wiped on second Helm deploy and then populated again once ArgoCD reboots.

I would advise setting `secret.createSecret` to false and managing the secret externally if you'd like ArgoCD to manage it's own secret.
