### ISSUE TITLE
Update argo-events chart to 0.16.0

### ISSUE THREAD

**Issue by iMoses** [argoproj/argo-helm#392]
the chart wasn't updated since 0.14.0

**Comment by arctiqtim** [comment]
Will second this one ... we use Helm to install all other Argo components via ArgoCD including Argo Events.  So we are currently stuck at 0.14.0  :(

**Comment by sudarshntn** [comment]
@VaibhavPage : As per this PR for the helm chart bump to 0.16 version https://github.com/argoproj/argo-helm/pull/409
I tried to bump it also I see their is a missing file "eventbus-controller-deployment.yaml" in the chart along with the eventsource-crd.yaml in the template folder. And by just getting these the deployment is successful. 

When i try to load the sample steps provided in the documentation - https://argoproj.github.io/argo-events/quick_start/

First, we need to setup event sources for gateway to listen.
Copied to clipboard
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/webhook.yaml
The event-source drives the configuration required for a gateway to consume events from external sources.

Create webhook gateway,
Copied to clipboard
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/gateways/webhook.yaml
After running above command, gateway controller will create corresponding a pod and service.

The issue is I am not able to see the pods or the service getting created. If I deploy the argo-events through the install.yaml then this steps are working fine.

Need some support on getting the latest updated Helm Charts made available.
