### ISSUE TITLE
Unable to install argo charts using helm 2.16.7 & Kubernetes 1.16

### ISSUE THREAD

**Issue by jaiawasthi** [argoproj/argo-helm#453]
**Describe the bug**
UPGRADE FAILED
Error: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
using argo chart  argo/argo --version 0.9.8 

**To Reproduce**
just use the given helm version & Kubernetes version
**Expected behavior**
Upgrade the workflow

**Additional context**
Unable to upgrade the workflow after upgrading to Kubernetes 1.16

**Comment by jaiawasthi** [comment]
Looked like something related to https://github.com/argoproj/argo-helm/pull/229 but i'm already tried using the latest chart version  0.12.0.

**Comment by jaiawasthi** [comment]
@benjaminws can you please provide any suggestions here please ?

**Comment by jaiawasthi** [comment]
Hi, can someone please help here ?

**Comment by seanson** [comment]
Hi @jaiawasthi - This is because your previous version contains a Deployment with api version `apps/v1beta2`, which has been deprecated in Kubernetes 1.16 and so Helm can't make the comparison. Unfortunately it's not something we can fix in the Helm chart.
Please see https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest or https://github.com/hickeyma/helm-mapkubeapis for some possible workarounds.
