### ISSUE TITLE
argo-cd: Deleting application in UI created by additionalApplications does not recreate

### ISSUE THREAD

**Issue by hobbsh** [argoproj/argo-helm#524]
**Describe the bug**
I have noticed that an application deleted in the UI that was created using `server.additionalApplications` in Argo CD does not recreate. I have to do a no-op `helm rollback` to current revision in order to get the CRD to recreate. This is because the CRDs are only creating during the `helm install/upgrade` and not created from a configmap or some other resource unaffected by deletes in the UI.

**To Reproduce**

1. Configure application in `server.additionalApplications` [here](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L597).
2. Once its created in the UI, delete it.
3. Observe it not recreating
4. Run `helm rollback -n argo argo-cd <CURRENT REVISION>` and it will recreate

**Expected behavior**
Deleting an application that is configured using `server.additionalApplications` should always recreate

**Additional context**
We use flux to deploy cluster-level components and could likely resolve this by moving the application specs to their own flat files and having flux just apply them. This is less convenient and I think something the `argo-cd` chart should support properly. I can not think of a way to solve this without some sort of controller + configmap combination.

**Comment by mkilchhofer** [comment]
Hi @hobbsh,
What you describe is an absolute normal behavior of helm - especially when using with flux. Everytime you bump a flux reconciliation or do a manual helm upgrade, helm checks if this resource exists and performs a 3-way merge (helm v3).

I think you get confused because you also use ArgoCD to deploy helm charts. What ArgoCD differentiates from flux (and other tools which executes `helm upgrade <foo>`) is that argo polls the repositories (every N minutes) and renders the templates. These templates then gets re-applied automatically (`application.spec.syncPolicy.automated`) or you can reapply them manually.

I think we can close this.

**Comment by mkilchhofer** [comment]
I'll close this now as the question should be answered. Feel free to reopen, if needed.

**Comment by hobbsh** [comment]
@mkilchhofer I don't really think this should be considered normal behavior. I feel like this is a very common use case and is in my opinion completely broken. Again, I don't know how to solve it but I don't think this issue should be closed.

**Comment by AntonWagenblass** [comment]
It came back after around 45 minutes...
