### ISSUE TITLE
ArgoCD can't update itself to 3.2.2

### ISSUE THREAD

**Issue by valerauko** [argoproj/argo-helm#703]
**Describe the bug**
I have a self-managed ArgoCD installation and it can't update itself to 3.2.2. Currently running 3.1.2.

The sync fails saying "one or more synchronization tasks are not valid" and below "Ingress.networking.k8s.io "" not found"

**To Reproduce**
I don't know if this is some problem with [my `values`](https://github.com/valerauko/sut/blob/a51d4a3/apps/20-argo-cd.yaml) or the chart itself. I couldn't see any changes in #659 (that bumped 3.2.2) related to ingress.

**Expected behavior**
ArgoCD can update itself without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/6322484/116429160-968c7600-a880-11eb-934f-ed1750a7a928.png)

**Additional context**
-

**Comment by rra** [comment]
I suspect your Kubernetes cluster is running a version prior to 1.19.

https://github.com/argoproj/argo-helm/pull/637 added support for specifying the ingress with API version `networking.k8s.io/v1`. The intent was to make this conditional on the capabilities of the Kubernetes cluster with conditionals like:
```
{{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion -}}
```
However, unfortunately this comparison doesn't work with the latest Argo CD because it isn't passing the appropriate flags to Helm v3. See https://github.com/argoproj/argo-cd/issues/5833.

**Comment by randrusiak** [comment]
By the way, we should use `.Capabilities.KubeVersion.` instead of .Capabilities.KubeVersion.GitVersion because it's marked as [deprecated](https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/pkg/chartutil/capabilities.go#L73).
But as @rra has noticed it won't work in argo without helm server-side validation.

**Comment by rra** [comment]
I'm not sure what the right fix for this is, because even when Argo CD fixes that bug, the running Argo CD won't be able to update the chart. Maybe temporarily revert #637 until Argo CD has fixed version comparisons in Helm templates?

**Comment by oliverbaehler** [comment]
@rra What if we added `kubeVersion` as values and considered it for comparison (if set compare to this version otherwise try to compare against capabilities? That's my best idea right now.

**Comment by rra** [comment]
Oh, yes, that's a good idea. It requires some work on the part of the person deploying the Helm chart, but it means not having to go backwards. That would work for me, certainly.

**Comment by oliverbaehler** [comment]
Already, i will cock up a patch

**Comment by valerauko** [comment]
Yes the cluster in question is running 1.18.2

**Comment by chgl** [comment]
Does `Capabilities.APIVersions.Has networking.k8s.io/v1` work better here? That helm feature was brought to my attention in https://github.com/argoproj/argo-helm/pull/312#discussion_r410735310

**Comment by oliverbaehler** [comment]
@chgl I have never noticed this, interesting. So we could have a generic template:

```
{{- define "argo-cd.capabilities.check" -}}
  {{- if  $.context.Capabilities.APIVersions.Has .capability -}}
    {{- true -}}
  {{- end -}}
{{- end -}}
```

And check for ingress like 

```
{{- if eq (include "argo-cd.capabilities.check" (dict "context" $ "capability" "networking.k8s.io/v1" )) }}
...
```
Would that make sense?

**Comment by chgl** [comment]
I'm not sure if it actually solves the problem of ArgoCD's helm templating, but it's a bit clearer compared to the semver check.

Do we need the template at this point, though? {{- if  .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}} seems more straight-forward to me.

**Comment by rra** [comment]
```
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
```
will return true for Kubernetes 1.18 because that version does exist (for`NetworkPolicy`), which is not what I think is wanted. I think you want:
```
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
```
However, per https://github.com/argoproj/argo-cd/issues/3594 this apparently also doesn't work because Argo CD doesn't pass `--validate` to `helm template`.
