### ISSUE TITLE
Helm charts releases

### ISSUE THREAD

**Issue by marcuz** [argoproj/argo-helm#742]
**Is your feature request related to a problem?**
Apologies for starting with a question, I couldn't find any old issue about this. Is there a reason why these Helm charts aren't released with semantic versioning?

**Describe the solution you'd like**
Release Helm charts changes using semantic versioning per-chart (e.g. https://github.com/prometheus-community/helm-charts/tags)

**Additional context**
I find it very difficult to know when there are changes/improvements/features/bugs with these Helm charts. In GitHub you can "watch all activities" or be notified about releases. Needless to say "all activities" gets very noisy. :)

P.S.: thank you everyone for contributing!

**Comment by oliverbaehler** [comment]
@marcuz I guess your issue is, that there are no releases (btw you can also subscribe to artifacthub feeds to get notified about new releases). We are rn addressing this issues, but have a difficult time since there's not a lot coperation from the repository owners. But with the new workflow your issue will be resolved: https://github.com/argoproj/argo-helm/pull/741

**Comment by marcuz** [comment]
Thank you, I will close this one and follow #741. :bow:
