### ISSUE TITLE
[argo-rollout] Add loadbalancer service and ingress for dashboard

### ISSUE THREAD

**Issue by cikupin** [argoproj/argo-helm#979]
### Is your feature request related to a problem?

I cannot connect to dashboad using public IP/endpoint. The only way to connect to argo-rollout dashboard is to port-forward dashboard service.

### Related helm chart

argo-rollouts

### Describe the solution you'd like

I want to be able to access my dashboard using public endpoint or IP. The solution is to create **Loadbalancer** service or **Ingress** to argo-rollout dashboard.

**Comment by mkilchhofer** [comment]
For Ingress there is already an existing issue: https://github.com/argoproj/argo-helm/issues/868

The problem that I see in this use case: The dashboard was designed as a kubectl plugin.

> The Argo Rollouts Kubectl plugin can serve a local UI Dashboard to visualize your Rollouts.
> 
> To start it, run kubectl argo rollouts dashboard in the namespace that contains your Rollouts. Then visit localhost:3100 to view the user interface.
> _Source: https://argoproj.github.io/argo-rollouts/dashboard/_

So all the dashboard functionality depended on the RBAC of your local kubeconfig file you are using. When this functionality was ported to a running pod inside the k8s cluster, you still need to port-forward with your local kubeconfig (and therefore your identity).

Now when we expose this dashboard via Ingress or service of type LoadBalancer, everyone have access to (maybe critical) information.

So I'd like to ask if you could open an issue in the [upstream project](https://github.com/argoproj/argo-rollouts) for this use case and maybe place a linkt to this issue here.
